# Generated by Django 5.1.4 on 2025-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_author_name_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
